version: "3.8"
services:
  tracker:
    image: financial-tracker:latest
    ports:
      - "3500:3500"
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    restart: always
    volumes:
      - './:/tracker'
    depends_on:
      - 'db'
    stdin_open: true
    tty: true
  db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=tracker
    image: mongo
    command: mongod --auth
    # ports:
    #   - '27017-27019:27017-27019'
    volumes:
      - db-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
volumes:
  db-data:
    driver: local