version: "3.8"
services:
  tracker:
    image: financial-tracker:latest
    ports:
      - "5000:5000"
    build: ./
    deploy:
      replicas: 1
    restart: always
  db:
    image: mongo:7.0.0-rc8
    volumes:
      - db-data:/data/db
    deploy:
      replicas: 1
    restart: always
volumes:
  db-data: